development:
  adapter: postgresql
  database: development-impact-monitor
  username: developer
  password: developer
  host: localhost
  port: 5432

production:
  adapter: postgresql
  database: <%= ENV['DB_NAME'] %>
  username: <%= ENV['DB_USER'] %>
  password: <%= ENV['DB_PASSWORD'] %>
  host: <%= ENV['DB_HOST'] %>
  port: 5432
